### ISSUE TITLE
Ограничить права на слой сообщений граждан

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_forest_violations#11]
В слой можно только добавлять сообщения из мобильного (группа гражданский мониторинг)
Удалять и менять нельзя.
При этом диспетчеру нужные полные права на модификацию слоя.

**Comment by BishopGIS** [comment]
Возможно стоит расширить модель прав НГВ на 
1. Данные:Запись(все права)
2. Данные:Запись(добавление)
3. Данные:Запись(изменение)
4. Данные:Запись(удаление)

**Comment by BishopGIS** [comment]
При чтении слоя для незарегистрированных пользователей не выдавать контакты и фильтровать почту (убирать домен, возможно затирать часть символов).

**Comment by NikitaFeodonit** [comment]
> для незарегистрированных пользователей не выдавать контакты и фильтровать почту

Если регистрированные пользователи могут быть в целом любыми людьми, то думаю, надо бы и в случае регистрированных делать ограничение на выдачу личной информации.

Можно ввести отдельный уровень доступа для сотрудников, которым уже будет даваться всё.

**Comment by BishopGIS** [comment]
Да, согласен

**Comment by BishopGIS** [comment]
Да, поле contact надо не показывать - хорошо бы настраивать права для полей.

**Comment by BishopGIS** [comment]
Реализовано через фильтры слоя. Все работает - закрываю.
