### ISSUE TITLE
Разработать сервис регистрации пользователей мобильного приложения для граждан

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_forest_violations#12]
При регистрации должен создаваться пользователь и добавляться в группу "Гражданский мониторинг"

**Comment by BishopGIS** [comment]
В качестве логина будет выступать адрес электронной почты. Необходимо выполнить простейшие проверки валидности адреса (наличие собаки, домена, зоны)

**Comment by dezhin** [comment]
Я добавил REST API для работы с пользователями и группами. При включенной настройке auth.register можно выполнить `POST /api/component/auth/user/` с параметрами пользователя `display_name`, `keyname`, `description`, `password` в ответе будет идентификатор нового пользователя.

Пока виджеты управления пользователя на это я не перевел, но в целом API работает. Нужно будет его еще перевести на сериализаторы, которые в ресурсах используются, чтобы работали корректные сообщения об ошибках.

Ну и нужно еще решить вопрос с назначаемыми по-умолчанию группами. Видимо это будет флаг в группе. Соответственно все группы с флагом будут назначаться при регистрации.

**Comment by dezhin** [comment]
Для назначения групп при регистрации я сделал флаг `register` у групп. Если он установлен, то группа назначается при регистрации автоматически.

**Comment by drnextgis** [comment]
Я обновил инстанс fv, вот пример запроса: http://176.9.38.120/fv/api/component/auth/user/4

**Comment by BishopGIS** [comment]
Правильно я понимаю, что для регистрации (выполнении запроса) необходимы права администратора?
Размещение в коде мобильного приложения логина и пароля администратора несекьюрно, да и поменяться оно может.
сейчас вот так ругается

```
401 Unauthorized

This server could not verify that you are authorized to access the document you requested.  Either you supplied the wrong credentials (e.g., bad password), or your browser does not understand how to supply the credentials required.
```

Или тут речь о том что бы к этому АПИ еще прикрутить сервис, который специально для нашей задачи?

**Comment by dezhin** [comment]
Нее, логин и пароль администратора конечно не нужно размещать в коде мобильного приложения. Я наверное не очень понятно написал. Еще раз попробую:

Нужно включить настройку `register = true` в секции `[auth]` config.ini и в этом случае `POST /api/component/auth/user/`  будет работать без логина и пароля администратора.

**Comment by BishopGIS** [comment]
Да, все ок. Секции [auth] не было.

**Comment by 4eRTuk** [comment]
Сейчас при запросе к `http://176.9.38.120/fv/api/component/auth/user/` выдается:

```
401 Unauthorized
This server could not verify that you are authorized to access the document you requested.  Either you supplied the wrong credentials (e.g., bad password), or your browser does not understand how to supply the credentials required.
```

**Comment by dezhin** [comment]
Сорри, это тут не отразили, в чатике было :) Для самостоятельной регистрации нужно делать ` POST /api/component/auth/register`, а `/api/component/auth/{user|group}/` только администраторам теперь доступно.

**Comment by 4eRTuk** [comment]
Понял.
