### ISSUE TITLE
Ограничение доступа к данным в строках по логину

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_forest_violations#14]
По аналогии с #11 необходимо обеспечить ограничение доступа к строкам:
У нас есть слой заметок инспекторов. Слой общий для всех инспекторов. 
Заводить на каждого инспектора по слою для заметок - не уверен что хорошая идея.
Но инспектора не должны читать заметки других.
В определенном поле хранится логин. Нужно, что бы при входе через веб интерфейс, а также через мобильное приложение были доступны только свои заметки.
Кстати задача типовая, когда выполняют сбор в общую таблицу, но не должны видеть чужие денные.

**Comment by drnextgis** [comment]
А что за логин хранится в определённом поле - это логин NGW или какой-то другой?

**Comment by BishopGIS** [comment]
Да, это логин НГВ. Сейчас есть 2 поля для фильтрации логин и некий уникальный идентификатор. Идентификатор предпочтительнее, ведь логин можно переименовать и тогда чужие заметки будут доступны не тому пользователю. А идентификатор инкрементный.
http://176.9.38.120/fv/resource/20
поля user_id и login

**Comment by drnextgis** [comment]
Насчёт переименование не понял, разве может пользователь изменить свой логин на логин другого пользователя, чтобы увидеть его заметки?

**Comment by drnextgis** [comment]
Я немного поэкспериментировал с фильтрами и вот в каком варианте что-то получилось:

1. Есть некий ресурс `Родитель` все пользователи могут в него писать, но на чтение данных он закрыт.
2. Создаём дочерний ресурс нового типа `Фильтр`, он пока в принципе не поддерживает запись, только чтение. На него мы даём права пользователям на чтение данных, накладывая фильтр вида `login={{user.keyname}}`, где `login` - атрибутивное поля родителя, а `{{user.keyname}}` - логин пользователя ngw, он будет браться из http запроса.
3. Мобильное пишет данные в `Родитель`, а отображает из `Фильтр`.

**Comment by BishopGIS** [comment]
Пользователь не может. Но администратор - может.
Например, человек уволился. Его логин заблокировали. Потом пришел однофамилец - ему выдали тот же логин. Вот тут может быть коллизия. Но если через логин проще, мы можем описать это в документации.

**Comment by drnextgis** [comment]
Да с логин проще. Мне кажется шарить один и тот же логин между разными пользователями - это какая-то странная практика, если администратор так сделает  - с него и спрос. Давай так и сделаем, вроде оно работает.

**Comment by BishopGIS** [comment]
Давай твой вариант с фильтром накатим на http://176.9.38.120/fv
И уже в мобильном будем реализовывать.

**Comment by BishopGIS** [comment]
Только по API - это даже лучше в данном случае.

**Comment by BishopGIS** [comment]
А можно в фильтр добавить еще ограничение по полям (колонкам)? Это бы решило #11

**Comment by BishopGIS** [comment]
Реализовано через фильтры слоя. Все работает - закрываю.
