### ISSUE TITLE
Добавить поддержку WMS Landsat Scanex

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_forest_violations#15]
Вроде бы по WMS проблем быть не должно!
 
ID слоя - 7E81339914D54801A50DD986FD4333AC,
WMS: http://maps.kosmosnimki.ru/TileService.ashx?map=7YP6Y&apikey=<your-api-key>
 
При запросе за слоем нужно дополнительно передавать те же параметры StartDate и EndDate, что и в TMS.

Пример рабочего запроса:

```
http://maps.kosmosnimki.ru/TileService.ashx/apikey84RY0J61QQ/map7YP6Y?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=11319355.09707938693463802,1252070.07706079818308353,20037508.34278919920325279,8207238.26216117851436138&CRS=EPSG:3857&WIDTH=1205&HEIGHT=960&LAYERS=7YP6Y.7E81339914D54801A50DD986FD4333AC&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE&StartDate=01.10.2015&EndDate=05.10.2015
```

Дата начала за две недели, дата окончания - текущая.

**Comment by drnextgis** [comment]
А TMS тут откуда взялся?

**Comment by BishopGIS** [comment]
Точно не помню, но суть в том что в мобильном надо отображать слой с ландсатом. Имеющийся источник WMS космоснимков. НГВ в мобильное этот WSM в виде ТМS должно отдавать.

**Comment by drnextgis** [comment]
Вроде сделал. Пришлось ввести специальную переменную URL `current_date`, пример фрагмента URL с датами: `StartDate={current_date-14}&EndDate={current_date}`. Пробелы внутри `{}` недопустимы. Вот пример такого ресурса [#79](http://192.168.250.154:6544/resource/79/update), а вот он на [карте](http://192.168.250.154:6544/resource/1/display).

**Comment by BishopGIS** [comment]
Done
