### ISSUE TITLE
Не работает фильтр на слое

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_forest_violations#17]
Должно вернуться 0 записей.
http://176.9.38.120/fv/api/resource/57/feature/?status=qqqq

На самом деле нам надо фильровать по полю status что бы получить новые лесоизменения, просто проверка показывает, что фильтрация не работает.

**Comment by drnextgis** [comment]
Проверь, пожалуйста, сейчас должно работать правильно.

**Comment by BishopGIS** [comment]
Вот такой запрос почему-то не работает http://176.9.38.120/fv/api/resource/57/feature/?bbox=15087905.000000,5947530.000000,16108892.000000,5970057.500000&status="Новое лесоизменение"
А если убрать status="Новое лесоизменение" - то работает.

**Comment by drnextgis** [comment]
Кавычки лишние.

**Comment by NikitaFeodonit** [comment]
Со стороны сервера всё корректно. Пришлось в НГМ разобраться с кодировкой русских букв. Теперь и там всё работает.
