### ISSUE TITLE
Сделать фильтр <>

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_forest_violations#18]
Необходимо фильтровать слой по датам. Например, вот так
http://176.9.38.120/fv/api/resource/57/feature/?date>'2005-06-01T00:00:00Z'

**Comment by drnextgis** [comment]
http://176.9.38.120/fv/api/resource/64/feature/?mdate={"gt":"2016-01-01T00:00:00Z","lt":"2016-03-01T00:00:00Z"}

Доступные операторы: lt(<), le(<=), eq(=), ne(<>), ge(>=), gt(>).

**Comment by BishopGIS** [comment]
Работает. Поддерживаются только поля даты.

**Comment by NikitaFeodonit** [comment]
Зашел под одним из логинов в браузере.

На запрос
http://176.9.38.120/fv/api/resource/57/feature/?bbox=14887794.000000,5868155.000000,15276673.000000,6154288.500000&status=Новое лесоизменение&date={"gt":"2016-01-02T00:00:00Z"}
получаю
[]
то есть пустой json.

На запрос
http://176.9.38.120/fv/api/resource/57/feature/?bbox=14887794.000000,5868155.000000,15276673.000000,6154288.500000&status=Новое лесоизменение
то есть без &date={"gt":"2016-01-02T00:00:00Z"}
получаю большой json с 167-ю записями.

На запрос
http://176.9.38.120/fv/api/resource/57/feature/?bbox=14887794.000000,5868155.000000,15276673.000000,6154288.500000&date={%22gt%22:%222016-01-02T00:00:00Z%22}
то есть без &status=Новое лесоизменение, но с &date={"gt":"2016-01-02T00:00:00Z"}
получаю
[]
то есть пустой json.

На запрос
http://176.9.38.120/fv/api/resource/57/feature/?&date={%22gt%22:%222016-01-02T00:00:00Z%22}
то есть только с &date={%22gt%22:%222016-01-02T00:00:00Z%22}
получаю json с 7-ю записями от нужной даты.


То есть date={} работает только сам по себе. В сочетании с другими полями не работает.

**Comment by NikitaFeodonit** [comment]
Должно быть по всем запросам с date={}, как помню, 7 записей.

**Comment by NikitaFeodonit** [comment]
Github порезал ссылки на запросы. Параметр должен быть с пробелом
"&status=Новое лесоизменение"

**Comment by drnextgis** [comment]
Всё равно не очевидно, что именно не так, там еще в некоторых запросах bbox фигурирует.

**Comment by NikitaFeodonit** [comment]
По запросу
http://176.9.38.120/fv/api/resource/57/feature/?bbox=14887794.000000,5868155.000000,15276673.000000,6154288.500000&status=Новое лесоизменение&date={"gt":"2016-01-02T00:00:00Z"}
должны отфильтроваться записи для данного bbox, с данным status'ом и старше данной даты. Но это не работает.
Без date={} выдает 167 записей с датами от сентября 2015 до февраля 2016. С date должно выдать записи только февральские.

**Comment by drnextgis** [comment]
Без даты я вообще не вижу ни одной записи за 2016 год по этому запросу:

```
http://176.9.38.120/fv/api/resource/57/feature/?bbox=14887794.000000,5868155.000000,15276673.000000,6154288.500000&status=Новое лесоизменение
```

**Comment by NikitaFeodonit** [comment]
Да, виноват, был не внимателен.

По запросу
http://176.9.38.120/fv/api/resource/57/feature/?status=Новое лесоизменение&date={"gt":"2015-10-02T00:00:00Z"}
выдает три записи.

Закрываю.
