### ISSUE TITLE
Разработать слой с историей

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_forest_violations#2]
Нужен векторный слой с поддержкой истории для получения массивов измененных идентификаторов.

По запросу получения изменений необходимо возвращать 3 массива идентифкаторов:
```json
{"deleted":[],
 "changed":[],
 "added":[]
}
```

В качестве базы предлагается использовать сервис **rosavto** поддержки истории.
Посему появляются 2 поля adate_beg и adate_end. И триггеры. 
Далее выявление новых и измененных объектов делается запросом когда поле adate_beg больше чем предыдущее время синхронизации, а удалённых - когда adate_end между временем предыдущей синхронизации и текущим.

Для получения текущего среза надо в запрос добавлять текущую дату.

**Comment by drnextgis** [comment]
Готово. Пример запроса:

```
http://176.9.38.120/fv/api/vector_layer/64/diff/?ts=2015-12-24%2007:35:27.483447
```

Ответ:

```json
{
	"deleted": [1, 30, 38, 37, 36, 18],
	"changed": [{
		"id": 6,
		"geom": "MULTIPOINT (4286911.9540524501353502 7573955.2551945913583040)",
		"fields": {
			"mtype": 2,
			"message": "\u041f\u0440\u043e\u0431\u0430",
			"author": "email2@email.com",
			"contact": "+79001234567",
			"status": 1,
			"stmessage": null,
			"mdate": {
				"year": 2015,
				"month": 9,
				"day": 8,
				"hour": 0,
				"minute": 0,
				"second": 0
			}
		},
		"extensions": {
			"description": "",
			"attachment": null
		}
	}],
	"added": []
}
```

**Comment by drnextgis** [comment]
Поменялся порядок вызова, теперь используются `ts_start` и `ts_end`, если передан только `ts_start`, то возвращаются все правки с момента `ts_start` до текущего, если только `ts_end` или вообще ничего не передано, то возвращаются вообще все правки с момента как слой стал отслеживаемым.

**Comment by BishopGIS** [comment]
Мне кажется можно закрывать. Вопрос с вложениями должен решаться новым типом слоя, когда вложение хрнится прямо в записи или как-то так, что бы была жесткая связь. На данном этапе это не нужно.
