### ISSUE TITLE
Проблема при регистрации пользователя через сервис

### ISSUE THREAD

**Issue by 4eRTuk** [nextgis/nextgisweb_forest_violations#20]
1. Почему-то не присваивается группа по-умолчанию для нового пользователя (test, test2...), хотя галочка отмечена.

2. Если указать при регистрации в качестве логина почту (foo@bar.baz), то регистрация проходит, но в панели управления в поле логин пишет "Указано недопустимое значение"
http://prntscr.com/9jru6r

**Comment by BishopGIS** [comment]
По п. 1 как воспроизвести?

**Comment by 4eRTuk** [comment]
Обычный POST на http://176.9.38.120/fv/api/component/auth/user/ с
телом `{"display_name": "test", "description": null, "keyname": "test", "password" : "test"}` через [REST Console](https://chrome.google.com/webstore/detail/rest-console/cokgbflfommojglbmbpenpphppikmonn?utm_source=chrome-app-launcher-info-dialog)

**Comment by BishopGIS** [comment]
Chrome нет, через curl не воспроизводится. У кого ни будь воспроизводится?

**Comment by yellow-sky** [comment]
В Хроме не воспроизводится пп1

**Comment by drnextgis** [comment]
Может дело в заголовке? Вот с таким точно работает:

```
Content-Type: application/json
```

**Comment by BishopGIS** [comment]
Серверу разве не все равно, если он в любом случае создает пользователя? Как может влиять на это заголовок?
Просто у Стаса, почему то группа по-умолчанию не назначается.

**Comment by drnextgis** [comment]
То есть пользователь создаётся, но группы не назначаются? Я просто подумал, что вообще процедура полностью не работает. Не знаю, у меня не воспроизводится.

**Comment by BishopGIS** [comment]
Да, именно так и только у Стаса. Можно посмотреть на этих юзеров вот тут: http://176.9.38.120/fv/auth/user/

**Comment by drnextgis** [comment]
У меня похоже тоже воспроизводится. Там же по идее при создании нового пользователя сейчас должна стоять галка у `Гражданский мониторинг`? Если да, то у меня тоже не устанавливается.

**Comment by BishopGIS** [comment]
Да, все верно. Посмотришь в чем дело?

**Comment by drnextgis** [comment]
Кажется я понял в чем дело, через curl ни у кого не должно воспроизводиться. Воспроизводится только через браузер. Причина - в том, что до этого, видимо, была произведена базовая аутентификация под админом и теперь браузер для всех запросов к данному хосту, начинающихся c `/api/` добавляет заголовок `Authorization`.
