### ISSUE TITLE
Отдается пустой список объектов

### ISSUE THREAD

**Issue by 4eRTuk** [nextgis/nextgisweb_forest_violations#26]
Похоже, параметр ts_start не учитываетя: http://176.9.38.120/fv/api/vector_layer/57/diff/?ts_start=1970-01-01T00:00:00Z&ts_end=2016-03-06T16:09:00Z

**Comment by drnextgis** [comment]
А зачем ты запрашиваешь историю с 1970 года? У нас не может дата выходить за рамки начала ведения истории, вот пример рабочего запроса: http://176.9.38.120/fv/api/vector_layer/57/diff/?ts_start=2016-03-07&ts_end=2016-06-06

**Comment by 4eRTuk** [comment]
А нельзя сделать, чтобы можно было? Ну например мне нужны все фичи, откуда я узнаю начало ведения истории?

**Comment by BishopGIS** [comment]
@4eRTuk Денис вот тут писал #2
```
Поменялся порядок вызова, теперь используются ts_start и ts_end, если передан только ts_start, то возвращаются все правки с момента ts_start до текущего, если только ts_end или вообще ничего не передано, то возвращаются вообще все правки с момента как слой стал отслеживаемым.
```
Т.е. ты в первый раз делаешь запрос только с ts_end. А потом уже ts_start становится равным ts_end прошлого раза. А текущий ts_end становится равным времени выполения запроса.
