### ISSUE TITLE
Нельзя сменить пароль или отключить пользователя

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_forest_violations#27]
Стоит запрет на изменение имени пользователя, который себя создал через мобильное приложение. В мобильном приложении имя пользователя - это электронная почта. В результате через админку нельзя поменять пароль или отключить пользователя не меняя логин.

**Comment by drnextgis** [comment]
Fixed via https://github.com/nextgis/nextgisweb/commit/aa3d31a8d14488461753da78a9acd7b5821f8db8
