### ISSUE TITLE
Сделать формирование схемы участка лесонарушения

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_forest_violations#7]
По идентификатору акта получать геометрии территории лесонарушения и формировать картинку заданных в запросе размеров. На картинке должно быть:
1. Положка
2. Лесоделение
3. Территория лесонарушения

Видимо это будет что-то наподобе век-карты - т.е. пользователь сам конфигурирует состав слоев (оформление в слое должно быть) и далее по новому АПИ запрашивает "сшитое" изображение (https://github.com/nextgis/nextgisweb/commit/457a70a2e8115f3f4f6af7001a139f83b0705006).

**Comment by drnextgis** [comment]
Вроде работает, но без подложки, [пример](http://176.9.38.120/fv/fvapi/schema/4?size=640,480)

**Comment by BishopGIS** [comment]
Все ок. Закрываю.
