### ISSUE TITLE
В API выдачи актов сделать возможность получения всех связанных документов и связанных с ними документов

### ISSUE THREAD

**Issue by BishopGIS** [nextgis/nextgisweb_forest_violations#8]
В запрос акта необходимо добавить ключ **traversal** для обхода по всем документам и связанным с ними документам. 
В результате использования ключа, если в связанном документе есть еще связанные документы, то должен формироваться вложенный массив related:
```json
{
   "related":{
      "docs":{
          "related":{
              ...
         }
      }
   }
}
```

**Comment by drnextgis** [comment]
Добавлено в https://github.com/nextgis/nextgisweb_forest_violations/commit/a47ea4bf8d447fa5868090746d147875520a19fa
